### ISSUE TITLE
Missing dlls

### ISSUE THREAD

**Issue by dkajan19** [thompsonnoahe/StreamDeckGpuLegacy#1]
The indicator does not work. I tried to run the attached exe file and it said I was missing the following components:
- MSVCP140D.dll
- ucrtbased.dll
- VCRUNTIME140_1D.dll
- VCRUNTIME140D.dll

I have installed the following:
- Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.40.33810
- Microsoft Visual C++ 2015-2022 Redistributable (x86) - 14.40.33810

from what I've read it's because it's released as dev and it doesn't support c++ redistributable. Please fix this problem.

**Comment by thompsonnoahe** [comment]
Hi @dkajan19!

Thanks for reaching out and for your feedback, it's appreciated! 🙏

This is a Stream Deck plugin, so I don't think the executable that's bundled within the .sdPlugin file is supposed to be run independently.

The bundled sdPlugin file should contain a Release version of the plugin, not Debug.

May I know a little more about how you tried to install the plugin or run the program? 

Thanks,

Noah

**Comment by dkajan19** [comment]
Hi @thompsonnoahe 

I installed the addon normally via double-click just like any other. The addon then displays correctly in the addon library but as soon as I add it to the screen only the background is displayed, no values are shown.

My graphics card is NVIDIA.

**Comment by thompsonnoahe** [comment]
Hi again @dkajan19,

What model is your GPU?

Thanks, 

Noah

**Comment by dkajan19** [comment]
@thompsonnoahe 1050TI

**Comment by thompsonnoahe** [comment]
Awesome, thanks for the info. What version of the NVIDIA driver do you have? You should be able to get this from GeForce Experience or the new NVIDIA app.

**Comment by dkajan19** [comment]
@thompsonnoahe I have 555.99 version of drivers.

**Comment by thompsonnoahe** [comment]
Thanks again for the info. Let me get back to you in a bit.

**Comment by thompsonnoahe** [comment]
Hi again, @dkajan19!

Can you try running `nvidia-smi.exe` on your machine if you have it? It should be located under `C:\Windows\System32`. 

Please send me a screenshot of the output.

The reason I ask is because I use NVML, a library for querying the utilization for NVIDIA cards. `nvidia-smi` does the same. I'd like to check to see if the utilization can be queried on your system at all.

Thanks!

Noah

**Comment by dkajan19** [comment]
Hi @thompsonnoahe, this is my output:

![image](https://github.com/thompsonnoahe/StreamDeckGpu/assets/148653376/5d165199-4487-41bb-bb98-2675ddb388e8)

**Comment by thompsonnoahe** [comment]
Strange, it looks like you're able to get the utilization from SMI. I'm not sure why the GPU metrics aren't working. Let me do some digging into this from NVIDIA's side. Thanks for your patience!

**Comment by dkajan19** [comment]
@thompsonnoahe well if you have any new info let me know for now thanks.

**Comment by thompsonnoahe** [comment]
Hey again, @dkajan19!

Can you send me your log file? It should be located in this path:

`C:\Users\<username>\AppData\Roaming\Elgato\StreamDeck\logs\com.nthompson.gpu<number>`

Feel free to send me all the files that have `com.nthompson.gpu`, I'll review them all for any issues.

Thanks,

Noah

**Comment by dkajan19** [comment]
Hi @thompsonnoahe, no log file from this addon is in the logs folder.

I am attaching zipped files of the addon.

[com.nthompson.gpu.sdPlugin.zip](https://github.com/user-attachments/files/16046227/com.nthompson.gpu.sdPlugin.zip)

**Comment by thompsonnoahe** [comment]
Hey again @dkajan19!

So unfortunately the PSU on my main PC died, so I'm without my repo at the moment 😟

Can you try reinstalling the add-on in the meantime from [Github](https://github.com/thompsonnoahe/StreamDeckGpu/releases/download/v1.0.0/com.nthompson.gpu.streamDeckPlugin)? Go to your Plugins on the right hand side of the Stream Deck app, and there should be an option to uninstall. You can also go into the settings panel and remove the plugin there. Please try reinstalling and see if that helps.

If not, let's see if we can re-attempt getting the logs. 😄 

Best,

Noah

**Comment by dkajan19** [comment]
@thompsonnoahe I tried as you said but still no success. No logs and no indication of GPU load.

**Comment by thompsonnoahe** [comment]
Hi @dkajan19,

I got my PC back up and running! 🥳

I tried running the executable in the zip archive you sent, no crash. I'll upload a new build and send it to you once I am able.

Thanks again for your patience!

Noah

**Comment by thompsonnoahe** [comment]
Hi again!

Just made a new build, can you try this one out?

Thanks!

Noah

[1.0.0.zip](https://github.com/user-attachments/files/16406028/1.0.0.zip)

**Comment by dkajan19** [comment]
Hi @thompsonnoahe, it's still not working for me. Now I'm getting a new error message glew32.dll missing.
![glew32](https://github.com/user-attachments/assets/a3bd439f-5a83-4a1f-b944-545ec5589609)

**Comment by thompsonnoahe** [comment]
Hi @dkajan19,

Try this version?

[1.0.0.zip](https://github.com/user-attachments/files/16432194/1.0.0.zip)

**Comment by dkajan19** [comment]
@thompsonnoahe same error

**Comment by thompsonnoahe** [comment]
Hi @dkajan19 

Hmm...let me try a different method do get this to work.

I'll get back to you soon!

Best,

Noah

**Comment by tomasstrejcek** [comment]
hey, similar problem, nothing shows in deck, the gpu wasnt executing because of glew32.dll missing, i downloaded glew 2.1.0 and glew 2.2.0 and tried their x64 dll, the gpu.exe runs bet nothing shows either in command line or when run directly, no logs either

win 11, drivers 556.12

**Comment by thompsonnoahe** [comment]
Hi there @dkajan19 and @tomasstrejcek!

Sorry about the issues. I appreciate your patience!

I have a new version coming soon your guys' way.

Stay tuned!

Noah

**Comment by thompsonnoahe** [comment]
Hey @dkajan19 and @tomasstrejcek!

I think this one is it! Try it below.

Please don't hesitate to reach out if there are any further issues.

[Release.zip](https://github.com/user-attachments/files/16435577/Release.zip)

**Comment by dkajan19** [comment]
@thompsonnoahe now it doesn't give me any error, but the Streamdeck still only shows the GPU image and no percentages.

**Comment by thompsonnoahe** [comment]
Hi @dkajan19 ,

Ok, glad to hear it solved the crash! Could you grab the logs from the logs folder?

Best,

Noah

**Comment by dkajan19** [comment]
> Hey again, @dkajan19!
> 
> Can you send me your log file? It should be located in this path:
> 
> `C:\Users\<username>\AppData\Roaming\Elgato\StreamDeck\logs\com.nthompson.gpu<number>`
> 
> Feel free to send me all the files that have `com.nthompson.gpu`, I'll review them all for any issues.
> 
> Thanks,
> 
> Noah

@thompsonnoahe I don't have any logs from this addon. I followed the comment above.

**Comment by thompsonnoahe** [comment]
Hi @dkajan19,

Can you send me the `StreamDeck0` log file? And can you try running the executable like you did before?

Best,

Noah

**Comment by tomasstrejcek** [comment]
works on my machine :) thanks

**Comment by dkajan19** [comment]
@thompsonnoahe I sent the log file to your email.

**Comment by thompsonnoahe** [comment]
Hi @dkajan19,

Thanks for sending that over! It does indeed look like the app is crashing on your system.

Quick question, do you have an integrated graphics card (iGPU) in your system? If you're not sure, feel free to send me a screenshot of your system specs.

Best,

Noah

**Comment by dkajan19** [comment]
@thompsonnoahe Yes I have an intel uhd 630.

**Comment by thompsonnoahe** [comment]
Ah, this is most likely the issue. `glGetString(GL_VENDOR)` is likely returning your integrated graphics card, rather than your dedicated card.

Can you try setting the preferred card for `gpu.exe` to "Use the high performance NVIDIA processor"? Or set it globally?

https://www.nvidia.com/content/Control-Panel-Help/vLatest/en-us/mergedProjects/nv3d/Manage_3D_Settings_(reference).htm

**Comment by dkajan19** [comment]
@thompsonnoahe I have it set globally and I have set it for gpu.exe as well but no results. I also set the exe in windows settings but still the same result.

**Comment by thompsonnoahe** [comment]
Hi @dkajan19,

Thanks again for working with me on this!

I think the issue will be resolved in a new feature update on working on, which will allow you to select which GPU you want to monitor, and uses DirectX over OpenGL for finding the GPU.

I'm hoping to get this pushed out soon.

I'll send it here in this chat and you can let me know the results.

Thanks,

Noah

**Comment by thompsonnoahe** [comment]
By the way, can you also try running the executable just so I can see what happens?

**Comment by dkajan19** [comment]
@thompsonnoahe I ran it and nothing happened. Also nothing has been written to the log file. When I ran it via cmd it gave a blank output.

**Comment by thompsonnoahe** [comment]
Ok, sounds like it's not crashing, just exiting due to the iGPU. I'm working on releasing the new version soon. Thanks again for helping out with this!

**Comment by thompsonnoahe** [comment]
Hey @dkajan19!

Can you try this one? This is the new version that allows you to select the GPU you want to monitor.

Also let me know the CPU usage? I'm noticing unusual CPU usage on my system and want to see if this is an issue with the plugin or just my system.

[1.2-pre.zip](https://github.com/user-attachments/files/16476859/1.2-pre.zip)

**Comment by dkajan19** [comment]
@thompsonnoahe as you can see in the picture below, I don't see any gpu to choose from
![image](https://github.com/user-attachments/assets/0e4d0878-8a4a-4786-bfa8-6a2934dd92a4)

**Comment by thompsonnoahe** [comment]
I think I'm getting a better understanding of the problem. Can you please run this command in PowerShell to confirm:

`wmic PATH Win32_videocontroller GET description`

**Comment by dkajan19** [comment]
@thompsonnoahe My output is as follows. It's due to the fact that I have displaylink docks.

- Intel(R) UHD Graphics 630
- DisplayLink USB Device
- DisplayLink USB Device
- NVIDIA GeForce GTX 1050 Ti

**Comment by thompsonnoahe** [comment]
Huh, the plugin should retrieve that 1050 TI by name and pull up that GPU.

Can we take a look at the logs?

**Comment by dkajan19** [comment]
@thompsonnoahe I've emailed it to you again

**Comment by thompsonnoahe** [comment]
Thanks! By any chance, did my plugin log anything?

**Comment by dkajan19** [comment]
@thompsonnoahe still your plugin didn't create any log for me

**Comment by thompsonnoahe** [comment]
Hi @dkajan19,

Can you zip up your logs folder and send them to me? I'd like to see the logs in their full context. Further, would it be okay if I shared your logs with Elgato? I'm wondering if they've seen this issue before where the plugin fails to start. From looking at your logs, it looks like the plugin never had a chance to start properly:

`2024-08-03T15:59:52.355Z                     StreamDeck                    wrn ESDCustomPluginClient::shutdown():              Shutdown of plugin 'com.nthompson.gpu' ended in invalid state..`

**Comment by dkajan19** [comment]
@thompsonnoahe of course, I've sent the folder to your email

**Comment by thompsonnoahe** [comment]
Hi @dkajan19,

A member of the Elgato team noticed that there is another plugin you have installed for monitoring the temp of your GPU installed. Can you try temporarily removing it and see if my plugin works?

Thanks!

Noah

**Comment by dkajan19** [comment]
@thompsonnoahe I removed it, reinstalled your plugin, but it still doesn't work.

**Comment by thompsonnoahe** [comment]
@dkajan19 Did you restart the Stream Deck app? You might need to restart it to get it running again.

**Comment by dkajan19** [comment]
@thompsonnoahe Yes, I turned the app off and on.

**Comment by thompsonnoahe** [comment]
Hi @dkajan19,

Let's try this:

Download v1.1.1 from the Releases page on GitHub.

Disable all other add-ons.

Install, restart your PC.

See if it works!

Thanks again,

Noah

**Comment by dkajan19** [comment]
@thompsonnoahe I followed your steps but without success.

**Comment by thompsonnoahe** [comment]
Hi again @dkajan19,

Sadly I don't think this is something we can resolve. It seems like your system has an issue I can't figure out.

In case you have any logs from my plugin, feel free to send them over. If not, it's nearly impossible for me to determine what the root cause of the issue is. It could be a variety of factors, such as GPU vendors, installation locations, etc that would make it difficult for me to support every configuration.

I will continue the support of this plugin, but unfortunately I can't determine what the root cause is on your system.

Thanks so much for working with me on this, @dkajan19! I sincerely apologize that we couldn't find the root cause. Hopefully in the future, something will change, but for now, without any detailed information from the logs, your system will remain unsupported.

Once again, my apologies, but thank you again for your support. I appreciate it. 🙂

If you have any further questions or concerns, please let me know. Please feel free to take any further steps to resolve the issue.

Many thanks and kind regards,

Noah

**Comment by dkajan19** [comment]
@thompsonnoahe I completely understand, but thank you anyway for the tremendous effort and I wish you a lot of success in this and other plugins. Maybe when I finally replace the machine I will use the plugin. Thanks again.

**Comment by thompsonnoahe** [comment]
Hi @dkajan19,

Not a problem! Happy to support.

Thank you! Have a good one 😁

All the best,

Noah
