### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by VfxTDwiki** [thompsonnoahe/StreamDeckGpuLegacy#2]
**Describe the bug**
I have noticed in the task manager that the process gpu.exe is using more than 15% of the CPU.

**To Reproduce**
1. Go to Task Manager
2. Click on Process
3. Sort by % of CPU Usage (high values first)
4. gpu.exe is one of the top in the list

**Expected behavior**
It shouldn't take that much CPU! 

**Screenshots**
<img width="502" alt="image" src="https://github.com/user-attachments/assets/cd5495af-7285-4037-9f56-1539717e42f4">

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - GPU: [NVIDIA RTX 4070 Laptop]
 - GPU Driver version: [552.12]
 - Version [1.0]

**Additional context**

**Comment by thompsonnoahe** [comment]
Hi @FXTDwiki,

Thanks for writing in about this issue! I am aware and will investigate.

I'll report back soon when I have some results to share.

Best, 

Noah

**Comment by thompsonnoahe** [comment]
Hi @FXTDwiki,

Can you try this version and let me know how much CPU it's using? This may solve the issue.

Thanks again,

Noah

[1.0.0.zip](https://github.com/user-attachments/files/16406022/1.0.0.zip)

**Comment by thompsonnoahe** [comment]
Hi @FXTDwiki,

Have you had a chance or try this and see if it works? 

Thanks,

Noah

**Comment by Svarshik23** [comment]
yes of course this version is outdated, but it does not load the processor so much and it seems that the GPU.exe process is not visible at all in the task manager
