### ISSUE TITLE
AMD GPU User

### ISSUE THREAD

**Issue by dcsublime** [thompsonnoahe/StreamDeckGpuLegacy#3]
I have recently downloaded the plugin and I am an AMD GPU user.  I have added this to the Stream Deck and upon pressing it I get the yellow triangle with and exclamation mark in the middle.  It doesn't seem anything executes or at least I notice nothing in the task manager.  

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU: AMD Radeon RX6900 XT
 - GPU Driver version: 24.5.1
 - Version 1.1

Thank you.

**Comment by thompsonnoahe** [comment]
Hi @dcsublime!

Thank you so much for trying out my plugin! Appreciate it :)

Do you get any metrics back from the icon? Or is it just a yellow exclamation mark? I haven't made this plugin perform any actions (yet), right now it just displays the utilization. Screenshots would be helpful.

Many thanks,

Noah

**Comment by dcsublime** [comment]
Hello Noah,

Sorry I should have been more through.  I am fairly technical, but have no stream deck dev or troubleshooting experience.  I would be glad to learn and help as an AMD tester if you need. 

I thought it would initialize when I pressed the button, but I suppose it should just display metrics when I place the button on the stream deck.  So I misunderstood.  

That aside, I do not get any display of utilization at all.  I only see the GPU graphic that is on the button by default. 
Please see the attached screenshot.  I have included the elgato CPU plugin in the screenshot so that you know it is functioning.  

Thank you for making this plugin available and for your response.  
![Screenshot 2024-07-31 121443](https://github.com/user-attachments/assets/cff6a302-77e8-4ed9-845c-3804a3b30cd2)

**Comment by thompsonnoahe** [comment]
Hi @dcsublime,

Thanks for your willingness to be a tester, it is really appreciated!

Would you mind grabbing the logs for me? It should be located here:

`C:\Users\<your-username>\AppData\Roaming\Elgato\StreamDeck\logs`

Feel free to zip them up and attach them in this chat.

Thanks,

Noah

**Comment by dcsublime** [comment]
Yes sir.  Logs are attached.

[logs.zip](https://github.com/user-attachments/files/16446446/logs.zip)

**Comment by thompsonnoahe** [comment]
Hi again @dcsublime,

Thanks so much! Doesn't look there are any logs from my app. Here's a couple things we can try:

1. Let's try to get logs from my app. Here's a new version that fixes some errors along with some more verbose logging: 
[1.1.1.zip](https://github.com/user-attachments/files/16446873/1.1.1.zip)

2. If that doesn't work, let's try just running the executable alone and see if it reports any errors: 
[com.nthompson.gpu.sdPlugin.zip](https://github.com/user-attachments/files/16446875/com.nthompson.gpu.sdPlugin.zip)


Thanks again for helping out!

Noah

**Comment by dcsublime** [comment]
Alright.  I have a few updates.  

I attempted several ways to install 1.1.1 into Stream Deck.  One was overwriting what was there.  Then I tried uninstalling your plugin and installing from the file and finally, I uninstalled the plugin and extracted the com.nthompson.gpu file then copied and pasted the com.nthompson.gpu.sdPlugin folder into apdata\elgato\StreamDeck\Plugins folder and then killed the stream deck application process and relaunched it.  
With all of these attempts, I would get a plugin , but it never said version 1.1.1 in the stream deck gui, it remained as 1.1.0. (I did notice that the manifest file included also still says 1.1.0, so I guess this is to be expected).  No matter which attempt, I experienced the same results.  Just an icon with no GPU metrics. 
Please see the screen shots regarding this and the most recent logs which I still see nothing in regards to this plugin in the logs. 
![image](https://github.com/user-attachments/assets/64db331f-9cd9-4b9b-8312-ac135a408911)
[logsAfter1.1.1Attempt.zip](https://github.com/user-attachments/files/16447310/logsAfter1.1.1Attempt.zip)


Next I attempted your steps from number two and ran the executable individually.  I could see a blank command prompt open and then I received the following error. 

![image](https://github.com/user-attachments/assets/12c02dab-3cf0-4266-902c-eb941742cf16)

As an additional step for testing,  I was on Stream Deck software version 6.6.1 and I updated to the latest 6.7.0.  I am still experiencing the same results.

**Comment by thompsonnoahe** [comment]
Hi again @dcsublime,

Thanks for this information, this really helps! Can you try this executable, and see if you get the same error?

[gpu.zip](https://github.com/user-attachments/files/16447640/gpu.zip)

**Comment by dcsublime** [comment]
Good day Sir,

I was away yesterday after my last response and I shutdown my PC.  Upon bootup and before I logged in, I received the following error.
![image](https://github.com/user-attachments/assets/3e2eeb8d-14c9-430c-863c-6c5133a1563d)
This dll is an nvidia dll and being that I am running AMD.  

I had hoped this would mean there would be something in the logs since it seemed that stream deck had tried to kickoff the gpu.exe.  After looking through the logs, I still don't see anything, but I will include them here. 
[logs.zip](https://github.com/user-attachments/files/16457709/logs.zip)

I have not tried your most recent request.  I will do that now, but wanted to keep this message separate.  I will follow up on the new executable soon.  

Thank you!

**Comment by dcsublime** [comment]
Hello Again Noah,

I have attempted the new executable  you have sent.  When executing, I got the following error.  
![image](https://github.com/user-attachments/assets/32f01001-f598-481f-9efd-597eade0e57b)
I am an administrator on the PC so this is not the cause.  

As a further bit of information, Norton does not like the executable and immediately removed it after I executed it.  
![image](https://github.com/user-attachments/assets/d8a70fe7-2f69-4ab5-82db-3c2d239b793c)

Thank you!

**Comment by thompsonnoahe** [comment]
Hi @dcsublime,

Looks like your antivirus deleted the executable. You can try redownloading it and whitelisting it, but it may be preferable for me just to send you a new version of the .sdPlugin.

I'll have a new one ready soon!

Thanks,

Noah

**Comment by thompsonnoahe** [comment]
Hi again @dcsublime,

Here's a new version that allows you to also select the GPU you want, can you try this one?

Also let me know the CPU usage? I'm noticing unusual CPU usage on my system and want to see if this is an issue with the plugin or just my system.

[1.2-pre.zip](https://github.com/user-attachments/files/16476866/1.2-pre.zip)

**Comment by thompsonnoahe** [comment]
Hi @dcsublime,

Any updates?

Noah

**Comment by dcsublime** [comment]
Hello Noah,  

Sorry for the delay.  I have been able to perform some testing with this new version.  It is very promising, but we still have some things to work on. Still very exciting to see it come along.  

When button is added to the Stream Deck we do now as you have said have the select GPU.  That works and I see my GPU in the dropdown.  For visuals as I walk through this, I have also left the Elgato CPU button in the screenshots.  
This first image is before I made the GPU selection
![image](https://github.com/user-attachments/assets/217fdbce-8e80-4801-84fc-bc005af7c018)

After I have made the GPU selection everything seems to be working nicely.  GPU % shows and CPU % seems to hover around normal.
![image](https://github.com/user-attachments/assets/a41d0eba-6803-4b1f-9dee-c9fcd54633c1)

Now if I move the GPU button sometimes it keeps the GPU selection in the dropdown and sometimes it looses it all together as shown in the screenshot below.  The Select GPU dropdown becomes empty and there are no selections at all. 
![image](https://github.com/user-attachments/assets/b16473ce-d223-48cf-b87c-6f6427d18b39)

I can get the button working again by deleting the button on the Stream Deck and ending the GPU.exe task in task manager.  Then adding the button back to the Stream Deck.  

Again I apologize for the delay, but hope this helps.  I should be around for a couple days before I have to leave again for a couple days.  Let me know how I can help further.

**Comment by thompsonnoahe** [comment]
Hi @dcsublime,

Wow, thanks so much for the detailed response! I really appreciate the effort! 🥇

Glad to see the metrics are working well! Regarding the other issue, let me try this on my system and try to reproduce the issue. 

As for the CPU usage, can you pull up Task Manager and see if `gpu.exe` is at the top? Or does it use only a little CPU time? Can you screenshot where it falls on the list and send it to me?

Thanks,

Noah

**Comment by SaintDoormatius-cmyk** [comment]
Just wanted to pipe in here as another AMD user and note that the "official" add-on for this from the Elgato site didn't work (everything was as originally shown above), but the 1.2 Pre release you posted here with the GPU selection option is working great now on my end.  A suggestion, if I may: could pressing the button result in it opening the AMD Adrenaline software (if installed)?  That would be handy!

**Comment by thompsonnoahe** [comment]
Hi @SaintDoormatius-cmyk,

Thanks for the feedback! So happy to hear that it works. I am planning on updating the "official" version on the Elgato store soon with the fixes in 1.1.1. Would you mind trying that out to verify that it works for AMD?

(Just a heads up, this one does not include a dropdown)

Link is here: https://github.com/thompsonnoahe/StreamDeckGpu/releases/tag/v1.1.1

Appreciate it!

Noah

**Comment by Svarshik23** [comment]
Hello, in version 1.1, the display from the AMD video card does not work
also in version 1.2.0, there is no display at all either and the video card selection item does not work
there seems to be a video card selection item, but when you click on it, nothing is shown

OC: Windows 11
Gpu: AMD Radeon rx580 4gb
GPU Driver Version: 23.11.1
plugin Vision: 1.1 / 1.2.0

![Снимок экрана 2024-08-23 213813](https://github.com/user-attachments/assets/28b30c81-4102-41c0-92e7-cbb7e82a7048)

[logs.zip](https://github.com/user-attachments/files/16732999/logs.zip)

Thank

**Comment by Svarshik23** [comment]
I also noticed after 3 hours of running the program that the plugin loads my processors by 14% when idling, and while the plugin is not working

OC: Windows 11
Cpu: AMD Ryzen 7 5800x 
Gpu: AMD Radeon rx580 4gb
GPU Driver Version: 23.11.1
plugin Vision: 1.2.0

![image (1)](https://github.com/user-attachments/assets/3abd5db8-cf78-4b43-81b3-78c0abe6646b)

**Comment by thompsonnoahe** [comment]
Hi @Svarshik23!

Can you see if you can try the v1.1.1 release? It's available [here](https://github.com/thompsonnoahe/StreamDeckGpu/releases/tag/v1.1.1).

If it's still not working, can you try extracting the logs again?

Thanks,

Noah

**Comment by Svarshik23** [comment]
Hi, it still didn't work, but I added the logs below.
According to your previous recommendations, I tried closing the program after installing the plugin and rebooting the computer, but it doesn't help


[logs 1.zip](https://github.com/user-attachments/files/16738133/logs.1.zip)

**Comment by thompsonnoahe** [comment]
Hi again @Svarshik23,

Thank you for trying out my Elgato plugin. I'm thinking that the RX 580 may not be supported by AMD for the ALDX library (which I use to get the utilization). Let me check to see if someone can get back to me on whether this GPU is supported.

Thanks,

Noah

**Comment by sc4t** [comment]
Bonjour! Le plugin fonctionne parfaitement sur mon Ordinateur. J'ai une 6800XT

**Comment by jscombs91** [comment]
@thompsonnoahe Just wanted to let you that the 1.2-pre version works for my RX 6700 XT but does have the side effect of gpu.exe taking 8-10% CPU usage. I do notice that it updates every 200-250ms so not sure if that has anything to do with it. (It looks like in the code the delay is 1000ms?) But the version 1.1.1 did not work at all for me.

**Comment by thompsonnoahe** [comment]
Hi @Svarshik23,

Apologies for the late reply, haven't had a lot of time to work on this.

I got a reply a while back from a user on the AMD forums, and it looks like the RX 5000-7000 series GPUs are supported by the FanControl plugin, which uses ADLX. I'm assuming this means that the RX 580 is not supported. I'll make a list of GPUs supported and tested by this plugin and put it in the README.

Thanks!

Noah

**Comment by thompsonnoahe** [comment]
> @thompsonnoahe Just wanted to let you that the 1.2-pre version works for my RX 6700 XT but does have the side effect of gpu.exe taking 8-10% CPU usage. I do notice that it updates every 200-250ms so not sure if that has anything to do with it. (It looks like in the code the delay is 1000ms?) But the version 1.1.1 did not work at all for me.

Hi @jscombs91,

Interesting find! I plan on picking up development on this again. If you wouldn't mind, can you collect some log files and send them to me for 1.1.1? They should be located at this path:

`C:\Users\<your-username>\AppData\Roaming\Elgato\StreamDeck\logs`

Best,

Noah

**Comment by thompsonnoahe** [comment]
Hi again @jscombs91,

Can you try this one out as well? I saw that AMD released a new version of ADLX, so this may help.

[1.1.1-test.zip](https://github.com/user-attachments/files/17605254/1.1.1-test.zip)

**Comment by StephenMotoGuy** [comment]
Tried the 1.1.1-test that you uploaded, it didn't detect the GPU at all.
[StreamDeck0.log](https://github.com/user-attachments/files/17891844/StreamDeck0.log)

The 1.2 worked well when running it. Haven't ran it for long though.

EDIT: I had this running for about 6 hours while gaming and the GPU usage never went above 8% while I was playing a game that other tools (Task manager, AMD Ryzen toolset, Saphire TRIXX, etc) showed 100% usage at some points. I am running a 7800 XT

**Comment by thompsonnoahe** [comment]
Hi @StephenMotoGuy,

I just uploaded a new version that introduces new fixes and improvements for the plugin. Try it out here: https://github.com/thompsonnoahe/StreamDeckGpu/releases/tag/v1.2

**Comment by thompsonnoahe** [comment]
Hi @SaintDoormatius-cmyk 

v1.2.1 is out and includes your feature request: https://github.com/thompsonnoahe/StreamDeckGpu/releases/tag/v1.2.1

Please keep in mind you must have AMD Adrenalin installed from AMD's website, not the UWP app that may come pre-installed on your computer.

NVIDIA users: please also use the new NVIDIA app, not GeForce Experience.

Noah

**Comment by jscombs91** [comment]
@thompsonnoahe Sorry for the late reply. Looks like the latest versions fixed the CPU usage for me.

**Comment by thompsonnoahe** [comment]
Closing this issue out as it is very stale. 

Everyone, please feel free to reopen if there are any further issues for AMD users.
