### ISSUE TITLE
Multi GPU

### ISSUE THREAD

**Issue by stellarcielo** [thompsonnoahe/StreamDeckGpuLegacy#4]
When there are two or more GPUs, is the utilization of one of the GPUs displayed? If so, do you plan to add an option to select which GPU's utilization is displayed?
Sorry for all the questions.

**Comment by thompsonnoahe** [comment]
Hi @Ratsnake!

Thanks for writing in.

Currently, my plugin picks the first GPU on a system that is either NVIDIA or AMD. Multi-GPU systems are currently unsupported.

Having said that, I am working on a new version that will allow you to select which GPU you want to monitor.

Thanks,

Noah

**Comment by stellarcielo** [comment]
Hello Noah!

Thanks for answering for my questions!

**Comment by thompsonnoahe** [comment]
Hi @Ratsnake!

You're welcome!

Noah
